DROP TABLE dog_dbti CASCADE CONSTRAINTS;
CREATE TABLE dog_dbti (
    DOGNO       NUMBER(10)    NOT NULL,
    E_PER       NUMBER(3)     DEFAULT 0,
    S_PER       NUMBER(3)     DEFAULT 0,
    A_PER       NUMBER(3)     DEFAULT 0,
    O_PER       NUMBER(3)     DEFAULT 0,
    -- 가상 컬럼: DBTI 결과 자동 합산 (예: ESAO)
    DBTI_TYPE   AS (
        (CASE WHEN E_PER >= 50 THEN 'E' ELSE 'I' END) ||
        (CASE WHEN S_PER >= 50 THEN 'S' ELSE 'N' END) ||
        (CASE WHEN A_PER >= 50 THEN 'A' ELSE 'T' END) ||
        (CASE WHEN O_PER >= 50 THEN 'O' ELSE 'U' END)
    ),
    UPDATE_DATE DATE          DEFAULT SYSDATE,
    
    CONSTRAINT PK_DOG_DBTI PRIMARY KEY (DOGNO),
    CONSTRAINT FK_DBTI_DOG FOREIGN KEY (DOGNO) REFERENCES dog(DOGNO) ON DELETE CASCADE,
    CONSTRAINT CHK_E_RANGE CHECK (E_PER BETWEEN 0 AND 100),
    CONSTRAINT CHK_S_RANGE CHECK (S_PER BETWEEN 0 AND 100),
    CONSTRAINT CHK_A_RANGE CHECK (A_PER BETWEEN 0 AND 100),
    CONSTRAINT CHK_O_RANGE CHECK (O_PER BETWEEN 0 AND 100)
);

COMMENT ON COLUMN DOG_DBTI.DBTI_TYPE IS '계산된 DBTI 유형(ESAO 등)';