DROP TABLE market_product CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MARKET_PRODUCT;

-- 마켓 상품 테이블 (MARKET)
-- ==========================================
CREATE TABLE market (
    PRODUCT_ID     NUMBER PRIMARY KEY,
    SELLER_ID      VARCHAR2(30) NOT NULL, -- 상품 등록자 (MEMBER 테이블의 ID 참조)
    CLASS_NAME     VARCHAR2(100) NOT NULL, -- 분류 (사료, 간식, 장난감 등)
    PRODUCT_NAME   VARCHAR2(200) NOT NULL,
    PRICE          NUMBER DEFAULT 0 NOT NULL,
    DELIVERY_FEE   NUMBER DEFAULT 0 NOT NULL, -- 배송비
    STOCK          NUMBER DEFAULT 0 NOT NULL, -- 재고 수량
    PRODUCT_DESC   CLOB, -- 상세 설명 (HTML 태그 포함 가능)
    PRODUCT_STATUS VARCHAR2(20) DEFAULT 'ON_SALE' NOT NULL, -- 판매 상태
    REG_DATE       DATE DEFAULT SYSDATE,
    -- 회원 테이블의 ID 컬럼 참조
    CONSTRAINT FK_MARKET_SELLER FOREIGN KEY (SELLER_ID) REFERENCES member(ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_MARKET NOCACHE;

-- 테이블 및 전체 컬럼 코멘트 
COMMENT ON TABLE market IS '강아지 마켓 상품 정보';
COMMENT ON COLUMN MARKET.PRODUCT_ID IS '상품 고유 번호 (PK)';
COMMENT ON COLUMN MARKET.SELLER_ID IS '판매자 아이디 (MEMBER.ID 참조)';
COMMENT ON COLUMN MARKET.CLASS_NAME IS '상품 분류명 (사료, 간식 등)';
COMMENT ON COLUMN MARKET.PRODUCT_NAME IS '상품명';
COMMENT ON COLUMN MARKET.PRICE IS '판매 가격';
COMMENT ON COLUMN MARKET.DELIVERY_FEE IS '배송비';
COMMENT ON COLUMN MARKET.STOCK IS '재고 수량';
COMMENT ON COLUMN MARKET.PRODUCT_DESC IS '상품 상세 본문 (CLOB)';
COMMENT ON COLUMN MARKET.PRODUCT_STATUS IS '판매 상태 (ON_SALE, SOLD_OUT)';
COMMENT ON COLUMN MARKET.REG_DATE IS '상품 등록 일시';

