-- 주문 상세 내역 테이블 (주문한 상품 하나하나를 기록)
CREATE TABLE market_order_item (
    ORDER_ITEM_ID   NUMBER PRIMARY KEY,        -- 상세 번호 (PK)
    ORDER_ID        NUMBER NOT NULL,           -- 부모 주문 번호 (FK)
    PRODUCT_ID      NUMBER NOT NULL,           -- 상품 번호 (FK)
    QUANTITY        NUMBER DEFAULT 1 NOT NULL, -- 주문 수량
    PRICE           NUMBER NOT NULL,           -- 주문 당시 상품 가격
    TOTAL_PRICE     NUMBER NOT NULL,           -- 합계 (수량 * 가격)
    CONSTRAINT FK_ITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES market_order(ORDER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ITEM_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES market(PRODUCT_ID)
);

-- 주문 상세용 시퀀스
CREATE SEQUENCE SEQ_MARKET_ORDER_ITEM START WITH 1 INCREMENT BY 1 NOCACHE;

COMMENT ON TABLE market_order_item IS '주문 상품 상세 내역';
COMMENT ON COLUMN MARKET_ORDER_ITEM.ORDER_ITEM_ID IS '상세 내역 고유 번호';
COMMENT ON COLUMN MARKET_ORDER_ITEM.ORDER_ID IS '부모 주문 번호';
COMMENT ON COLUMN MARKET_ORDER_ITEM.PRODUCT_ID IS '주문한 상품 번호';
COMMENT ON COLUMN MARKET_ORDER_ITEM.QUANTITY IS '주문 수량';
COMMENT ON COLUMN MARKET_ORDER_ITEM.PRICE IS '단가';
COMMENT ON COLUMN MARKET_ORDER_ITEM.TOTAL_PRICE IS '결제 금액(단가*수량)';


COMMIT;