
--  상품 이미지 테이블 (PRODUCT_IMAGE)
CREATE TABLE product_image (
    IMAGE_ID    NUMBER PRIMARY KEY,
    PRODUCT_ID  NUMBER NOT NULL,
    FILE_NAME   VARCHAR2(500) NOT NULL, -- 서버에 저장될 파일명
    FILE_PATH   VARCHAR2(1000),         -- (추가 권장) 저장 폴더 경로
    IS_MAIN     CHAR(1) DEFAULT 'N' NOT NULL CHECK (IS_MAIN IN ('Y', 'N')), 
    IMAGE_ORDER NUMBER DEFAULT 1,       -- (추가 권장) 이미지 노출 순서
    REG_DATE    DATE DEFAULT SYSDATE,
    -- 참조 테이블명을 MARKET으로 수정
    CONSTRAINT FK_IMAGE_PRODUCT FOREIGN KEY (PRODUCT_ID) 
        REFERENCES market(PRODUCT_ID) ON DELETE CASCADE
);

-- 2. 시퀀스 및 코멘트 마무리
CREATE SEQUENCE SEQ_PRODUCT_IMAGE NOCACHE;

COMMENT ON TABLE product_image IS '상품별 다중 이미지 관리 (1:N)';
COMMENT ON COLUMN PRODUCT_IMAGE.IMAGE_ID IS '이미지 고유 번호';
COMMENT ON COLUMN PRODUCT_IMAGE.PRODUCT_ID IS '참조 상품 번호';
COMMENT ON COLUMN PRODUCT_IMAGE.FILE_NAME IS '변경 저장된 파일명';
COMMENT ON COLUMN PRODUCT_IMAGE.IS_MAIN IS '대표 이미지 여부 (Y/N)';
COMMENT ON COLUMN PRODUCT_IMAGE.IMAGE_ORDER IS '이미지 정렬 순서';
COMMENT ON COLUMN PRODUCT_IMAGE.REG_DATE IS '이미지 등록일';
